### ISSUE TITLE
Empty menu on home page on mobile viewport

### ISSUE THREAD

**Issue by sniok** [headlamp-k8s/headlamp#2066]
![image](https://github.com/headlamp-k8s/headlamp/assets/4517681/9f6f8c87-6277-4e11-ae96-f489a2f3947b)

the three dot menu on the right opens an empty menu. on desktop it's not visible

**Comment by skoeva** [comment]
Is this issue the same as #1719?

**Comment by illume** [comment]
Yeah, this was the same issue and it's fixed now. AFAIK

**Comment by sniok** [comment]
This is still an issue, the ticket mentioned above is unrelated. The menu that's not working is in top right

![image](https://github.com/user-attachments/assets/1fa20752-a83e-4d81-a26d-bd3352f97070)

**Comment by sniok** [comment]
On the home view it's empty. On other views (like on your screenshot) if you click not directly on the icon it will do a ripple effect but nothing happens

**Comment by skoeva** [comment]
Ah I see. Will look into this
